export const states = [ 
    {value: "Andhra Pradesh"},
    {value: "Arunachal Pradesh"},
    {value: "Assam"},
    {value: "Bihar"},
    {value: "Chhattisgarh"},
    {value: "Goa"},
    {value: "Gujarat"},
    {value: "Haryana"},
    {value: "Himachal Pradesh"},
    {value: "Jammu and Kashmir"},
    {value: "Jharkhand"},
    {value: "Karnataka"},
    {value: "Kerala"},
    {value: "Madhya Pradesh"},
    {value: "Maharashtra"},
    {value: "Manipur"},
    {value: "Meghalaya"},
    {value: "Mizoram"},
    {value: "Nagaland"},
    {value: "Odisha"},
    {value: "Punjab"},
    {value: "Rajasthan"},
    {value: "Sikkim"},
    {value: "Tamil Nadu"},
    {value: "Telangana"},
    {value: "Tripura"},
    {value: "Uttarakhand"},
    {value: "Uttar Pradesh"},
    {value: "West Bengal"},
    {value: "Chandigarh"},
    {value: "Delhi"}
]